import type { IAgentRunRequest } from '@noema/api-client/agents';
import type { EmbeddedAgentName, IAgentCapability } from './types';

export const AGENT_CAPABILITIES: Record<EmbeddedAgentName, IAgentCapability> = {
  'cognitive-copilot': {
    name: 'cognitive-copilot',
    title: 'Cognitive Copilot',
    shortLabel: 'Copilot',
    description: 'Turns live learning state into a calm, learner-safe readout.',
    preparationDescription: 'A short explanation of what your current learning state suggests.',
    surface: ['dashboard', 'copilot', 'session-summary'],
    whenToSurface: 'After dashboard data, session progress, or fresh hints reveal a next action.',
    actionLabel: 'Ask Copilot',
    requiredContext: ['userId'],
    defaultExecution: 'auto',
    learnerVisible: true,
    risk: 'low',
  },
  'mental-debugger': {
    name: 'mental-debugger',
    title: 'Mental Debugger',
    shortLabel: 'Reasoning check',
    description: 'Explains what happened in a Step from metacognition-owned trace evidence.',
    preparationDescription: 'A short breakdown of where your reasoning held up and where it slipped.',
    surface: ['active-session', 'session-summary'],
    whenToSurface: 'After an answer, hesitation, skip, or confusing Step.',
    actionLabel: 'Explain my reasoning',
    requiredContext: ['userId'],
    defaultExecution: 'realtime',
    learnerVisible: true,
    risk: 'medium',
  },
  'calibration-coach': {
    name: 'calibration-coach',
    title: 'Calibration Coach',
    shortLabel: 'Calibration',
    description: 'Compares confidence with reasoning quality and suggests a small adjustment.',
    preparationDescription: 'A brief coaching note about how your confidence matches your reasoning.',
    surface: ['dashboard', 'session-summary'],
    whenToSurface: 'After reviews or summaries show confidence drift or uncertainty.',
    actionLabel: 'Check calibration',
    requiredContext: ['userId'],
    defaultExecution: 'realtime',
    learnerVisible: true,
    risk: 'low',
  },
  'patch-planner-remediation-agent': {
    name: 'patch-planner-remediation-agent',
    title: 'Patch Planner',
    shortLabel: 'Repair plan',
    description: 'Turns diagnostic signals into minimum-sufficient repair proposals.',
    preparationDescription: 'A small, reviewable repair plan before anything changes.',
    surface: ['session-summary', 'content', 'knowledge'],
    whenToSurface: 'When a Step, concept, or content item needs a repair path.',
    actionLabel: 'Draft repair',
    requiredContext: ['userId'],
    defaultExecution: 'realtime',
    reviewRoute: '/content/review',
    learnerVisible: true,
    risk: 'medium',
  },
  'strategy-replanning-agent': {
    name: 'strategy-replanning-agent',
    title: 'Strategy Replanner',
    shortLabel: 'Replan',
    description: 'Suggests the smallest safe adjustment to the active session strategy.',
    preparationDescription: 'A small adjustment to the next steps in the current session.',
    surface: ['active-session'],
    whenToSurface: 'During an active session when the learner is blocked, skipping, or waiting.',
    actionLabel: 'Adjust next steps',
    requiredContext: ['userId', 'sessionId'],
    defaultExecution: 'realtime',
    reviewRoute: '/session/new',
    learnerVisible: true,
    risk: 'high',
  },
  'ingestion-concept-extraction-agent': {
    name: 'ingestion-concept-extraction-agent',
    title: 'Concept Extractor',
    shortLabel: 'Extract concepts',
    description: 'Finds concept candidates and evidence in uploaded source material.',
    preparationDescription: 'A draft list of concept candidates and supporting evidence.',
    surface: ['content', 'curriculum'],
    whenToSurface: 'After source material exists but before graph or curriculum drafting.',
    actionLabel: 'Extract concepts',
    requiredContext: ['userId'],
    defaultExecution: 'batch',
    reviewRoute: '/knowledge',
    learnerVisible: true,
    risk: 'medium',
  },
  'knowledge-graph-agent': {
    name: 'knowledge-graph-agent',
    title: 'Knowledge Graph Agent',
    shortLabel: 'Graph proposal',
    description: 'Proposes anchors, prerequisite edges, misconceptions, and graph review items.',
    preparationDescription: 'A graph proposal with suggested concept links and structural changes to review.',
    surface: ['knowledge', 'content', 'curriculum'],
    whenToSurface: 'When selected concepts need anchoring or graph structure.',
    actionLabel: 'Draft graph suggestions',
    requiredContext: ['userId', 'conceptIds'],
    defaultExecution: 'batch',
    reviewRoute: '/knowledge?workspace=review&agent=knowledge-graph-agent',
    learnerVisible: true,
    risk: 'high',
  },
  'curriculum-outline-planner': {
    name: 'curriculum-outline-planner',
    title: 'Curriculum Goal Analyzer',
    shortLabel: 'Analyze goal',
    description: 'Turns a learner goal into candidate concept anchors, prerequisites, and a provisional path to review.',
    preparationDescription: 'A goal-first concept proposal you can confirm before the final curriculum is drafted.',
    surface: ['curriculum'],
    whenToSurface: 'At the start of curriculum creation, before a durable path is generated.',
    actionLabel: 'Analyze goal',
    requiredContext: ['userId'],
    defaultExecution: 'realtime',
    reviewRoute: '/curricula/new',
    learnerVisible: true,
    risk: 'medium',
  },
  'curriculum-planner': {
    name: 'curriculum-planner',
    title: 'Curriculum Planner',
    shortLabel: 'Plan path',
    description: 'Drafts a curriculum path from an approved concept anchor set and readiness data.',
    preparationDescription: 'A durable, reviewable path draft created after concept approval.',
    surface: ['curriculum'],
    whenToSurface: 'After goal analysis and concept approval, or when inspecting a path or preparing a session.',
    actionLabel: 'Draft curriculum',
    requiredContext: ['userId', 'conceptIds'],
    defaultExecution: 'batch',
    reviewRoute: '/curricula',
    learnerVisible: true,
    risk: 'high',
  },
  'curriculum-revision-agent': {
    name: 'curriculum-revision-agent',
    title: 'Curriculum Revision Agent',
    shortLabel: 'Revise path',
    description: 'Drafts reviewable structural revisions for an existing curriculum.',
    preparationDescription: 'A reviewable set of structural changes for the current curriculum.',
    surface: ['curriculum'],
    whenToSurface: 'When a learner wants to restructure an existing path without editing it directly.',
    actionLabel: 'Draft revision',
    requiredContext: ['userId', 'curriculumId'],
    defaultExecution: 'batch',
    reviewRoute: '/curricula',
    learnerVisible: true,
    risk: 'high',
  },
  'content-creation-orchestrator': {
    name: 'content-creation-orchestrator',
    title: 'Content Orchestrator',
    shortLabel: 'Content draft',
    description: 'Preflights graph, learner state, pedagogy, and grounding before content drafting.',
    preparationDescription: 'A ready-to-review content drafting setup with the needed context assembled.',
    surface: ['content', 'knowledge', 'curriculum'],
    whenToSurface: 'When a concept has insufficient practice material or a repair needs content.',
    actionLabel: 'Prepare content draft',
    requiredContext: ['userId', 'conceptIds'],
    defaultExecution: 'realtime',
    reviewRoute: '/content/review',
    learnerVisible: true,
    risk: 'medium',
  },
  'content-creator-agent': {
    name: 'content-creator-agent',
    title: 'Content Creator',
    shortLabel: 'Create content',
    description: 'Creates reviewable cards and Step Activity variants from ready context.',
    preparationDescription: 'A reviewable content draft with cards or activity variants.',
    surface: ['content'],
    whenToSurface: 'After orchestration confirms the content prompt is ready.',
    actionLabel: 'Generate content',
    requiredContext: ['userId', 'conceptIds'],
    defaultExecution: 'batch',
    reviewRoute: '/content/review',
    learnerVisible: false,
    risk: 'medium',
  },
  'lesson-plan-generator': {
    name: 'lesson-plan-generator',
    title: 'Lesson Plan Generator',
    shortLabel: 'Lesson plan',
    description: 'Prepares a reviewable LessonPlan for a selected curriculum/session slice.',
    preparationDescription: 'A reviewable lesson plan draft for the selected session or path.',
    surface: ['curriculum', 'active-session'],
    whenToSurface: 'Before a curriculum-bound session starts or when reviewing a path.',
    actionLabel: 'Prepare lesson plan',
    requiredContext: ['userId', 'sessionId'],
    defaultExecution: 'realtime',
    reviewRoute: '/session/new',
    learnerVisible: true,
    risk: 'high',
  },
  'mode-preference-helper': {
    name: 'mode-preference-helper',
    title: 'Mode Preference Helper',
    shortLabel: 'Mode choice',
    description: 'Chooses among already eligible epistemic modes using recent preferences.',
    preparationDescription: 'A short recommendation for which mode fits best right now.',
    surface: ['active-session', 'curriculum'],
    whenToSurface: 'When several valid modes are available and a short tie-break helps.',
    actionLabel: 'Suggest mode',
    requiredContext: ['userId'],
    defaultExecution: 'realtime',
    learnerVisible: true,
    risk: 'low',
  },
};

export function getAgentCapability(agentName: EmbeddedAgentName): IAgentCapability {
  return AGENT_CAPABILITIES[agentName];
}

export function missingAgentContext(
  capability: IAgentCapability,
  request: Partial<IAgentRunRequest>
): string[] {
  return capability.requiredContext.filter((field) => {
    const value = request[field];
    if (Array.isArray(value)) {
      return value.length === 0;
    }
    return value === undefined || value === null || value === '';
  });
}
