// =============================================================================
// TYPES INDEX - Re-export all types from a single entry point
// =============================================================================
// Import types from here: import { User, Card, Deck } from '@manthanein/shared/types';

// User & Authentication types
export type {
  UserId,
  DeckId,
  CardId,
  ReviewId,
  PluginId,
  AchievementId,
  SessionId,
  TagId,
  AuthProvider,
  SubscriptionTier,
  UserPreferences,
  User,
  UserLearningStats,
} from "./user.types";

// Card types - The heart of the system
export type {
  CardType,
  AtomicCardContent,
  ClozeCardContent,
  ClozeItem,
  ImageOcclusionContent,
  OcclusionRegion,
  ImageLabel,
  OcclusionLayer,
  AudioCardContent,
  ProcessCardContent,
  ProcessStep,
  ComparisonCardContent,
  ComparisonItem,
  ComparisonFeature,
  HiddenCell,
  ExceptionCardContent,
  ExceptionItem,
  ErrorSpottingContent,
  ErrorItem,
  ConfidenceCardContent,
  ConfidenceLevel,
  ConceptGraphContent,
  ConceptNode,
  ConceptRelation,
  RelationType,
  CaseBasedContent,
  CaseInfoItem,
  CaseOption,
  DecisionNode,
  MultimodalContent,
  MultimodalElement,
  ElementInteraction,
  TransferCardContent,
  TransferHint,
  ProgressiveDisclosureContent,
  ProgressiveLevel,
  RichText,
  MediaAttachment,
  MathBlock,
  CardContent,
  Card,
  CardSRSState,
  CardState,
  Rating,
  NumericRating,
  CardStats,
} from "./card.types";

// Re-export RatingValues constant and utilities
export { RatingValues, NumericToRating, toRating } from "./card.types";

// Deck & Organization types
export type {
  Deck,
  DeckSettings,
  DeckStats,
  DeckCollaborator,
  Tag,
  StudySession,
  SessionType,
  SessionSettings,
  ReviewRecord,
} from "./deck.types";

export { DEFAULT_DECK_SETTINGS, SYSTEM_TAGS } from "./deck.types";

// Scheduler & Algorithm types
export type {
  SchedulerType,
  BaseSchedulerConfig,
  FSRSConfig,
  FSRSWeights,
  HLRConfig,
  HLRFeatureWeights,
  SM2Config,
  LeitnerConfig,
  SchedulerConfig,
  SchedulingResult,
  SimpleSchedulingResult,
  IntervalPrediction,
  SchedulingContext,
  FatigueAdjustment,
} from "./scheduler.types";

export {
  DEFAULT_FSRS_WEIGHTS,
  DEFAULT_FSRS_CONFIG,
  DEFAULT_HLR_CONFIG,
  DEFAULT_SM2_CONFIG,
  DEFAULT_LEITNER_CONFIG,
  getDefaultSchedulerConfig,
} from "./scheduler.types";

// Gamification types
export type {
  XPConfig,
  Level,
  LevelPerk,
  StreakData,
  StreakMilestone,
  StreakReward,
  MemoryIntegrityScore,
  MemoryIntegritySnapshot,
  AchievementCategory,
  AchievementRarity,
  Achievement,
  AchievementRequirement,
  UserAchievement,
  MasteryBadge,
  MasteryLevel,
  CalibrationScore,
  CalibrationBucket,
  SkillTree,
  SkillNode,
  SkillEdge,
  ReflectionPrompt,
  ReflectionOption,
  ReflectionResponse,
  LearningStrategy,
  BurnoutIndicators,
  BurnoutIndicator,
  BurnoutRecommendation,
} from "./gamification.types";

export {
  DEFAULT_XP_CONFIG,
  MASTERY_REQUIREMENTS,
  LEARNING_STRATEGIES,
  BURNOUT_INDICATORS,
} from "./gamification.types";

// Plugin types
export type {
  PluginCategory,
  PluginCapability,
  PluginManifest,
  PluginAuthor,
  PluginPermission,
  PluginConfigSchema,
  PluginConfigProperty,
  InstalledPlugin,
  PluginLifecycle,
  CardGenerationPlugin,
  FileInput,
  ParsedContent,
  ContentSection,
  ExtractedEntity,
  ExtractedRelationship,
  CardSuggestion,
  CardGenerationOptions,
  GeneratedCard,
  ValidationResult,
  ValidationError,
  ValidationWarning,
  SchedulingPlugin,
  ReviewHistoryItem,
  ScoringPlugin,
  ScoringInput,
  ScoringResult,
  FeedbackResult,
  Correction,
  VisualizationPlugin,
  VisualizationInput,
  VisualizationOutput,
  VisualizationRenderer,
  MetaLearningPlugin,
  LearningPatternAnalysis,
  ForgettingPattern,
  LearningRecommendation,
  StrategyEvaluation,
  PluginRegistry,
  PluginAPI,
  CardAPI,
  DeckAPI,
  ReviewAPI,
  UserAPI,
  StorageAPI,
  NetworkAPI,
  UIAPI,
  AIAPI,
  EventAPI,
} from "./plugin.types";

// API types
export type {
  APIResponse,
  APIError,
  APIMeta,
  PaginationParams,
  PaginatedResponse,
  LoginRequest,
  LoginResponse,
  RegisterRequest,
  OAuthLoginRequest,
  RefreshTokenRequest,
  PasswordResetRequest,
  UserDTO,
  UserStatsDTO,
  UpdateProfileRequest,
  UpdatePreferencesRequest,
  DeckDTO,
  DeckStatsDTO,
  CreateDeckRequest,
  UpdateDeckRequest,
  UpdateDeckSettingsRequest,
  CardSummaryDTO,
  CardDTO,
  CardSRSStateDTO,
  CardStatsDTO,
  CreateCardRequest,
  BulkCreateCardsRequest,
  UpdateCardRequest,
  CardFilter,
  StartSessionRequest,
  SessionSettingsDTO,
  StudySessionDTO,
  NextCardResponse,
  SchedulingOptionsDTO,
  IntervalOptionDTO,
  SessionProgressDTO,
  SubmitReviewRequest,
  SubmitReviewResponse,
  EndSessionRequest,
  EndSessionResponse,
  SessionSummaryDTO,
  AchievementDTO,
  ImportRequest,
  ImportOptions,
  ImportProgressDTO,
  ExportRequest,
  ExportResponse,
  SyncRequest,
  SyncChange,
  SyncResponse,
  SyncConflict,
  AnalyticsTimeRange,
  StudyAnalyticsDTO,
  DailyStatsDTO,
  DeckAnalyticsDTO,
  RetentionDataPoint,
  HeatmapDataPoint,
  WSEventType,
  WSMessage,
} from "./api.types";

// Settings types - Professional-grade settings system
export type {
  SettingsId,
  ConfigSnapshotId,
  ConfigChangeId,
  LKGCId,
  PluginSettingsId,
  ReviewOrder,
  NewCardPosition,
  LeechAction,
  SettingsScope,
  SettingsScopeContext,
  ScopeMetadata,
  SettingExplanation,
  OptionExplanation,
  SettingMetadata,
  SettingType,
  SettingValidation,
  SettingsCategory,
  CategoryMetadata,
  // SchedulerType is exported from scheduler.types.ts above
  FSRSParameters,
  StudySettings,
  ThemeMode,
  FontSize,
  FontFamily,
  CardAnimation,
  DisplaySettings,
  HapticIntensity,
  AutoplaySpeed,
  AudioSettings,
  EmailDigestFrequency,
  NotificationSettings,
  PrivacySettings,
  SyncFrequency,
  ConflictResolution,
  SyncSettings,
  AccessibilitySettings,
  AISettings,
  ExportFormat,
  AdvancedSettings,
  PluginSettingsSection,
  PluginSettingsInjection,
  SettingsState,
  ScopedSettings,
  ConfigChangeSource,
  ConfigChange,
  ConfigCheckpoint,
  CheckpointChangesSummary,
  CategoryChangeSummary,
  LKGCAutoCriteria,
  LKGCEntry,
  LKGCPerformanceSnapshot,
  LKGCSuggestion,
  EffectiveSettings,
  SettingsConflict,
  SettingsActions,
} from "./settings.types";

export {
  DEFAULT_FSRS_PARAMETERS,
  DEFAULT_LKGC_CRITERIA,
} from "./settings.types";

// Settings metadata with explanations
export {
  CATEGORY_METADATA,
  STUDY_SETTINGS_METADATA,
  DISPLAY_SETTINGS_METADATA,
  AUDIO_SETTINGS_METADATA,
  NOTIFICATION_SETTINGS_METADATA,
  PRIVACY_SETTINGS_METADATA,
  SYNC_SETTINGS_METADATA,
  ACCESSIBILITY_SETTINGS_METADATA,
  AI_SETTINGS_METADATA,
  ADVANCED_SETTINGS_METADATA,
  // Keyed metadata for easy access
  STUDY_METADATA,
  DISPLAY_METADATA,
  AUDIO_METADATA,
  NOTIFICATION_METADATA,
  PRIVACY_METADATA,
  SYNC_METADATA,
  ACCESSIBILITY_METADATA,
  AI_METADATA,
  ADVANCED_METADATA,
  getSettingMetadata,
} from "./settings-metadata";

// =============================================================================
// LKGC - Local Knowledge Graph Controller Domain Model
// =============================================================================
// Core domain model for the cognitive substrate that powers learning.
// LKGC is NOT a database - it's a typed property graph with explicit
// provenance, privacy, sync, and explainability built-in.

// Foundation types (identity, provenance, privacy, sync)
export type {
  EntityId,
  DeviceId,
  UserId as LKGCUserId,
  SessionId as LKGCSessionId,
  NodeId,
  EdgeId,
  EventId,
  ProposalId,
  SnapshotId,
  RevisionNumber,
  Confidence,
  Probability,
  Timestamp,
  Duration,
  DataSource,
  Provenance,
  PrivacyLevel,
  TelemetryConsent,
  PrivacyScope,
  MergeStrategy,
  SyncState,
  ConflictState,
  LKGCEntity,
  NormalizedValue,
  BipolarScore,
  Percentage,
} from "./lkgc/foundation";

export {
  DEFAULT_TELEMETRY_CONSENT,
  DEFAULT_PRIVACY_SCOPE,
} from "./lkgc/foundation";

// Node types (knowledge graph vertices)
export type {
  NodeType,
  BaseNode,
  MediaType,
  CardNode,
  ContentBlock,
  CardModel,
  SchedulingState,
  NoteNode,
  ConceptNode as LKGCConceptNode,
  TermNode,
  FactNode,
  FormulaNode,
  FormulaVariable,
  ProcedureNode,
  ProcedureStep,
  ExampleNode,
  CounterexampleNode,
  QuestionNode,
  ResourceNode,
  ResourceHighlight,
  ChunkNode,
  GoalNode,
  GoalTarget,
  LearningPathNode,
  LearningPathStep,
  MilestoneNode,
  MilestoneCriterion,
  AssessmentNode,
  AssessmentItem,
  AssessmentAttempt,
  AssessmentAnswer,
  RubricNode,
  RubricCriterion,
  RubricLevel,
  StrategyNode,
  ReflectionNode,
  ReflectionContent,
  PredictionNode,
  ErrorPatternNode,
  QuestNode,
  QuestObjective,
  QuestRequirements,
  ChallengeNode,
  BadgeNode,
  StreakRuleNode,
  StreakRequirement,
  BossNode,
  BossPhase,
  RewardNode,
  RewardContent,
  PluginModuleNode,
  PluginCapability as LKGCPluginCapability,
  ExperimentNode,
  ExperimentVariant,
  ExperimentResults,
  NotificationTemplateNode,
  NotificationTrigger,
  LKGCNode,
  NodeOfType,
} from "./lkgc/nodes";

export { isNodeType } from "./lkgc/nodes";

// Edge types (knowledge graph relationships)
export type {
  EdgeType,
  EdgePolarity,
  BaseEdge,
  PrerequisiteOfEdge,
  PartOfEdge,
  ExplainsEdge,
  CausesEdge,
  AnalogousToEdge,
  ExampleOfEdge,
  CounterexampleOfEdge,
  DerivedFromEdge,
  DefinesEdge,
  UsesEdge,
  ContrastsWithEdge,
  ContrastDifference,
  TargetsGoalEdge,
  IntroducedInPathStepEdge,
  AssessedByEdge,
  PracticedByEdge,
  BestLearnedWithStrategyEdge,
  ErrorPatternForEdge,
  ReflectionAboutEdge,
  FrequentlyConfusedWithEdge,
  CrossDeckDuplicateOfEdge,
  MentionsEdge,
  BacklinkEdge,
  LKGCEdge,
  EdgeOfType,
  EdgeDirection,
  EdgeQueryPredicate,
} from "./lkgc/edges";

export { isEdgeType } from "./lkgc/edges";

// Mastery state (multi-dimensional learning state)
export type {
  MasteryGranularity,
  MasteryState,
  MemoryState,
  EvidenceAggregate,
  ReviewOutcomeCounts,
  TimeOfDay,
  MetacognitionState,
  MasteryCalibration,
  StrategyUsageMetrics,
  MasterySelfRegulation,
  ReflectionMetrics as MasteryReflectionMetrics,
  ForgettingState,
  GeneralizationState,
  CognitiveLoadState,
  AffectState,
  AffectiveMetric,
  TrustState,
  MasteryStateDelta,
  MasteryUpdateReason,
  MasterySnapshot,
  MasteryFeatureVector,
  RecentHistorySummary,
  PeriodSummary,
  RelatedNodeSummary,
} from "./lkgc/mastery";

// Session & timeline (learning as a process)
export type {
  SessionMode,
  SessionGoalType,
  StudySession as LKGCStudySession,
  ReviewAttemptId,
  SessionGoal,
  SessionPause,
  SessionInterruption,
  PacingProfile,
  SessionStatistics,
  MoodCapture,
  EnvironmentContext,
  ReviewRating,
  ReviewAttempt,
  ReviewTiming,
  ReviewResponse,
  AnswerChange,
  ReviewEdit,
  HintUsage,
  HintReveal,
  ReviewInteraction,
  ScrollingBehavior,
  TouchPatterns,
  PreReviewState,
  PostReviewState,
  ReviewMetacognition,
  ReflectionArtifact,
  ReflectionStructuredContent,
  PlannedAdjustment,
  ReflectionQualityAssessment,
  ReflectionInsight,
  ActionItem,
  TimelineEntry,
  TimelineEntryType,
} from "./lkgc/session";

// Events (strict event taxonomy)
export type {
  EventCategory,
  BaseEvent,
  ReviewPerformanceEventType,
  ReviewStartedEvent,
  ReviewCompletedEvent,
  AnswerRevealedEvent,
  HintRequestedEvent,
  AnswerChangedEvent,
  CardEditedEvent,
  CardSuspendedEvent,
  CardFlaggedEvent,
  MetacognitiveEventType,
  ConfidenceReportedEvent,
  RecallForecastEvent,
  FeelingOfKnowingEvent,
  ErrorAttributionEvent,
  StrategySelectedEvent,
  EffortReportedEvent,
  ReflectionSubmittedEvent,
  AttentionEventType,
  IdleDetectedEvent,
  AppBackgroundedEvent,
  AppForegroundedEvent,
  NotificationReceivedEvent,
  DeckSwitchedEvent,
  ScrollActivityEvent,
  RapidFailDetectedEvent,
  GraphExploredEvent,
  SpeedrunDetectedEvent,
  StallDetectedEvent,
  GamificationEventType,
  QuestAcceptedEvent,
  QuestCompletedEvent,
  QuestAbandonedEvent,
  ChallengeStartedEvent,
  ChallengeCompletedEvent,
  ChallengeFailedEvent,
  BadgeEarnedEvent,
  StreakExtendedEvent,
  StreakBrokenEvent,
  StreakFrozenEvent,
  BossAttemptedEvent,
  BossDefeatedEvent,
  BossFailedEvent,
  RewardClaimedEvent,
  LevelUpEvent,
  XpGainedEvent,
  ContentEventType,
  ImportStartedEvent,
  ImportCompletedEvent,
  ImportFailedEvent,
  DuplicateMergedEvent,
  TagEditedEvent,
  LinkCreatedEvent,
  LinkDeletedEvent,
  NodeCreatedEvent,
  NodeUpdatedEvent,
  NodeDeletedEvent,
  EnvironmentEventType,
  SessionEnvironmentCapturedEvent,
  ConnectivityChangedEvent,
  TimeZoneChangedEvent,
  DeviceChangedEvent,
  ReviewPerformanceEvent,
  MetacognitiveEvent,
  AttentionEvent,
  GamificationEvent,
  ContentEvent,
  EnvironmentEvent,
  LKGCEvent,
} from "./lkgc/events";

export { isEventCategory } from "./lkgc/events";

// Aggregation pipeline
export type {
  RawEventEntry,
  EventBatch,
  FeatureGranularity,
  BaseDerivedFeature,
  AttemptFeatures,
  SessionFeatures,
  DailyFeatures,
  WeeklyFeatures,
  DerivedFeature,
  StateUpdateBatch,
  StateTransition,
  StateTransitionCause,
  AISnapshot,
  SnapshotPurpose,
  GlobalFeatures,
  PendingDecision,
  AIProposal,
  ProposalType,
  ProposalStatus,
  ProposalContent,
  SchedulingProposal,
  DifficultyAdjustmentProposal,
  CoachingInterventionProposal,
  GamificationTriggerProposal,
  ContentSuggestionProposal,
  StrategyRecommendationProposal,
  GoalAdjustmentProposal,
  DecisionRationale,
  FeatureContribution,
  Counterfactual,
  UserProposalResponse,
  ProposalApplicationResult,
  AuditedChange,
  ChangeInitiator,
  AffectedEntity,
  FieldChange,
  RollbackInfo,
  AggregationPipelineConfig,
} from "./lkgc/aggregation";

// Explainability artifacts
export type {
  DecisionRationaleRecord,
  DecisionType,
  FeatureAnalysis,
  FeatureDetail,
  FeatureInteraction,
  ModelInfo,
  CounterfactualAnalysis,
  RequiredChange,
  RationaleSummary,
  UncertaintyAnalysis,
  UncertaintySource,
  UncertaintyReductionStrategy,
  CoachingInterventionRecord,
  InterventionType,
  TriggerCondition,
  InterventionContent,
  RelatedLink,
  PersonalizationInfo,
  UserInteractionRecord,
  UserFeedback,
  InterventionEffect,
  InterventionMetrics,
  InterventionUplift,
  ExplanationTemplate,
  PlaceholderDefinition,
  TemplateCondition,
  GeneratedInsight,
  InsightType,
  InsightContent,
  InsightVisualization,
  InsightEvidence,
  EvidenceItem,
  InsightActionability,
  SuggestedAction,
  ExplanationAudit,
  ExplanationQualityMetrics,
  ExplanationFeedback,
} from "./lkgc/explainability";

// Meta-learning metrics
export type {
  MetricsCollection,
  MetricsPeriod,
  MetricsHealth,
  MetricWarning,
  CalibrationMetrics,
  BrierScoreMetric,
  ECEMetric,
  CalibrationBin,
  CalibrationBiasMetric,
  ResolutionMetric,
  MetacognitiveSensitivityMetric,
  DunningKrugerMetric,
  CorrelationMetric,
  CalibrationByDifficulty,
  EfficiencyMetrics,
  StabilityTrendMetric,
  ForgettingCurveFitMetric,
  IntervalFitError,
  TimeToMasteryMetric,
  HintDependencyMetric,
  SpacingQualityMetric,
  InterferenceMetric,
  ConfusionPair,
  ReviewEfficiencyMetric,
  RetentionRateMetric,
  LapseRateMetric,
  StrategyMetrics,
  StrategyDiversityMetric,
  StrategyAdherenceMetric,
  StrategyEfficacyMetric,
  StrategyEffectiveness,
  ReflectionCompletionMetric,
  ReflectionQualityMetric,
  PlanFollowThroughMetric,
  StrategySelectionMetric,
  SelfRegulationMetrics,
  SessionConsistencyMetric,
  FatigueIndexMetric,
  FlowProxyMetric,
  FrictionScoreMetric,
  StreakHealthMetric,
  GoalAlignmentMetric,
  ProcrastinationMetric,
  SelfEfficacyMetric,
  TransferMetrics,
  GeneralizationScoreMetric,
  ConceptCoverageMetric,
  ErrorPatternMetric,
  ExplanationQualityMetric,
  CrossContextMetric,
  AnalogicalReasoningMetric,
  IntegrationScoreMetric,
  MetricsQuery,
  MetricCategory,
  MetricsComparison,
  MetricsChanges,
  MetricChange,
  MetricThresholds,
} from "./lkgc/metrics";

export { DEFAULT_METRIC_THRESHOLDS } from "./lkgc/metrics";
