// =============================================================================
// TYPES INDEX - Re-export all types from a single entry point
// =============================================================================
// Import types from here: import { User, Card, Deck } from '@manthanein/shared/types';

// User & Authentication types
export type {
  UserId,
  DeckId,
  CardId,
  ReviewId,
  PluginId,
  AchievementId,
  SessionId,
  TagId,
  AuthProvider,
  SubscriptionTier,
  UserPreferences,
  User,
  UserLearningStats,
} from "./user.types";

// Card types - The heart of the system
export type {
  CardType,
  AtomicCardContent,
  ClozeCardContent,
  ClozeItem,
  ImageOcclusionContent,
  OcclusionRegion,
  ImageLabel,
  OcclusionLayer,
  AudioCardContent,
  ProcessCardContent,
  ProcessStep,
  ComparisonCardContent,
  ComparisonItem,
  ComparisonFeature,
  HiddenCell,
  ExceptionCardContent,
  ExceptionItem,
  ErrorSpottingContent,
  ErrorItem,
  ConfidenceCardContent,
  ConfidenceLevel,
  ConceptGraphContent,
  ConceptNode,
  ConceptRelation,
  RelationType,
  CaseBasedContent,
  CaseInfoItem,
  CaseOption,
  DecisionNode,
  MultimodalContent,
  MultimodalElement,
  ElementInteraction,
  TransferCardContent,
  TransferHint,
  ProgressiveDisclosureContent,
  ProgressiveLevel,
  RichText,
  MediaAttachment,
  MathBlock,
  CardContent,
  Card,
  CardSRSState,
  CardState,
  Rating,
  NumericRating,
  CardStats,
} from "./card.types";

// Re-export RatingValues constant and utilities
export { RatingValues, NumericToRating, toRating } from "./card.types";

// Deck & Organization types
export type {
  Deck,
  DeckSettings,
  DeckStats,
  DeckCollaborator,
  Tag,
  StudySession,
  SessionType,
  SessionSettings,
  ReviewRecord,
} from "./deck.types";

export { DEFAULT_DECK_SETTINGS, SYSTEM_TAGS } from "./deck.types";

// Scheduler & Algorithm types
export type {
  SchedulerType,
  BaseSchedulerConfig,
  FSRSConfig,
  FSRSWeights,
  HLRConfig,
  HLRFeatureWeights,
  SM2Config,
  LeitnerConfig,
  SchedulerConfig,
  SchedulingResult,
  SimpleSchedulingResult,
  IntervalPrediction,
  SchedulingContext,
  FatigueAdjustment,
} from "./scheduler.types";

export {
  DEFAULT_FSRS_WEIGHTS,
  DEFAULT_FSRS_CONFIG,
  DEFAULT_HLR_CONFIG,
  DEFAULT_SM2_CONFIG,
  DEFAULT_LEITNER_CONFIG,
  getDefaultSchedulerConfig,
} from "./scheduler.types";

// Gamification types
export type {
  XPConfig,
  Level,
  LevelPerk,
  StreakData,
  StreakMilestone,
  StreakReward,
  MemoryIntegrityScore,
  MemoryIntegritySnapshot,
  AchievementCategory,
  AchievementRarity,
  Achievement,
  AchievementRequirement,
  UserAchievement,
  MasteryBadge,
  MasteryLevel,
  CalibrationScore,
  CalibrationBucket,
  SkillTree,
  SkillNode,
  SkillEdge,
  ReflectionPrompt,
  ReflectionOption,
  ReflectionResponse,
  LearningStrategy,
  BurnoutIndicators,
  BurnoutIndicator,
  BurnoutRecommendation,
} from "./gamification.types";

export {
  DEFAULT_XP_CONFIG,
  MASTERY_REQUIREMENTS,
  LEARNING_STRATEGIES,
  BURNOUT_INDICATORS,
} from "./gamification.types";

// Plugin types
export type {
  PluginCategory,
  PluginCapability,
  PluginManifest,
  PluginAuthor,
  PluginPermission,
  PluginConfigSchema,
  PluginConfigProperty,
  InstalledPlugin,
  PluginLifecycle,
  CardGenerationPlugin,
  FileInput,
  ParsedContent,
  ContentSection,
  ExtractedEntity,
  ExtractedRelationship,
  CardSuggestion,
  CardGenerationOptions,
  GeneratedCard,
  ValidationResult,
  ValidationError,
  ValidationWarning,
  SchedulingPlugin,
  ReviewHistoryItem,
  ScoringPlugin,
  ScoringInput,
  ScoringResult,
  FeedbackResult,
  Correction,
  VisualizationPlugin,
  VisualizationInput,
  VisualizationOutput,
  VisualizationRenderer,
  MetaLearningPlugin,
  LearningPatternAnalysis,
  ForgettingPattern,
  LearningRecommendation,
  StrategyEvaluation,
  PluginRegistry,
  PluginAPI,
  CardAPI,
  DeckAPI,
  ReviewAPI,
  UserAPI,
  StorageAPI,
  NetworkAPI,
  UIAPI,
  AIAPI,
  EventAPI,
} from "./plugin.types";

// API types
export type {
  APIResponse,
  APIError,
  APIMeta,
  PaginationParams,
  PaginatedResponse,
  LoginRequest,
  LoginResponse,
  RegisterRequest,
  OAuthLoginRequest,
  RefreshTokenRequest,
  PasswordResetRequest,
  UserDTO,
  UserStatsDTO,
  UpdateProfileRequest,
  UpdatePreferencesRequest,
  DeckDTO,
  DeckStatsDTO,
  CreateDeckRequest,
  UpdateDeckRequest,
  UpdateDeckSettingsRequest,
  CardSummaryDTO,
  CardDTO,
  CardSRSStateDTO,
  CardStatsDTO,
  CreateCardRequest,
  BulkCreateCardsRequest,
  UpdateCardRequest,
  CardFilter,
  StartSessionRequest,
  SessionSettingsDTO,
  StudySessionDTO,
  NextCardResponse,
  SchedulingOptionsDTO,
  IntervalOptionDTO,
  SessionProgressDTO,
  SubmitReviewRequest,
  SubmitReviewResponse,
  EndSessionRequest,
  EndSessionResponse,
  SessionSummaryDTO,
  AchievementDTO,
  ImportRequest,
  ImportOptions,
  ImportProgressDTO,
  ExportRequest,
  ExportResponse,
  SyncRequest,
  SyncChange,
  SyncResponse,
  SyncConflict,
  AnalyticsTimeRange,
  StudyAnalyticsDTO,
  DailyStatsDTO,
  DeckAnalyticsDTO,
  RetentionDataPoint,
  HeatmapDataPoint,
  WSEventType,
  WSMessage,
} from "./api.types";

// Settings types - Professional-grade settings system
export type {
  SettingsId,
  ConfigSnapshotId,
  ConfigChangeId,
  LKGCId,
  PluginSettingsId,
  ReviewOrder,
  NewCardPosition,
  LeechAction,
  SettingsScope,
  SettingsScopeContext,
  ScopeMetadata,
  SettingExplanation,
  OptionExplanation,
  SettingMetadata,
  SettingType,
  SettingValidation,
  SettingsCategory,
  CategoryMetadata,
  // SchedulerType is exported from scheduler.types.ts above
  FSRSParameters,
  StudySettings,
  ThemeMode,
  FontSize,
  FontFamily,
  CardAnimation,
  DisplaySettings,
  HapticIntensity,
  AutoplaySpeed,
  AudioSettings,
  EmailDigestFrequency,
  NotificationSettings,
  PrivacySettings,
  SyncFrequency,
  ConflictResolution,
  SyncSettings,
  AccessibilitySettings,
  AISettings,
  ExportFormat,
  AdvancedSettings,
  PluginSettingsSection,
  PluginSettingsInjection,
  SettingsState,
  ScopedSettings,
  ConfigChangeSource,
  ConfigChange,
  ConfigCheckpoint,
  CheckpointChangesSummary,
  CategoryChangeSummary,
  LKGCAutoCriteria,
  LKGCEntry,
  LKGCPerformanceSnapshot,
  LKGCSuggestion,
  EffectiveSettings,
  SettingsConflict,
  SettingsActions,
} from "./settings.types";

export {
  DEFAULT_FSRS_PARAMETERS,
  DEFAULT_LKGC_CRITERIA,
} from "./settings.types";

// Settings metadata with explanations
export {
  CATEGORY_METADATA,
  STUDY_SETTINGS_METADATA,
  DISPLAY_SETTINGS_METADATA,
  AUDIO_SETTINGS_METADATA,
  NOTIFICATION_SETTINGS_METADATA,
  PRIVACY_SETTINGS_METADATA,
  SYNC_SETTINGS_METADATA,
  ACCESSIBILITY_SETTINGS_METADATA,
  AI_SETTINGS_METADATA,
  ADVANCED_SETTINGS_METADATA,
  // Keyed metadata for easy access
  STUDY_METADATA,
  DISPLAY_METADATA,
  AUDIO_METADATA,
  NOTIFICATION_METADATA,
  PRIVACY_METADATA,
  SYNC_METADATA,
  ACCESSIBILITY_METADATA,
  AI_METADATA,
  ADVANCED_METADATA,
  getSettingMetadata,
} from "./settings-metadata";
