// =============================================================================
// MANTHANEIN SHARED PACKAGE









































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































};  META_LEARNING_UNLOCKS,  DEFAULT_SKILL_TREES,  ACHIEVEMENTS,export {// =============================================================================// EXPORTS// =============================================================================}  return new GamificationManager(options);}): GamificationManager {  metaLearningUnlocks?: ReadonlyArray<MetaLearningUnlock>;  skillTrees?: ReadonlyArray<SkillTree>;export function createGamificationManager(options?: { */ * Create a new gamification manager instance/**// =============================================================================// FACTORY FUNCTIONS// =============================================================================}  }    };      comboUpdate: { newCombo, comboLost },      newMetaLearningUnlocks,      newAchievements,      xpTransaction,    return {        const newCombo = comboLost ? 0 : userState.currentCombo + 1;    const comboLost = review.rating === 1; // "Again" breaks combo    // Update combo        );      userState.metaLearningUnlocks      userState.stats,    const newMetaLearningUnlocks = this.metaLearning.checkUnlocks(    // Check meta-learning unlocks        );      userState.unlockedAchievements      userState.stats,    const newAchievements = this.achievements.checkUnlocks(    // Check achievements        }      }        xpTransaction.amount = xpResult.remaining;      if (xpTransaction.amount > xpResult.remaining) {      // Cap at remaining allowed            );        userState.streakDays        userState.currentCombo,        review.responseTimeMs,        review.cardDifficulty,        review.rating,      xpTransaction = this.xp.calculateReviewXP(    if (xpResult.allowed) {        let xpTransaction: XPTransaction | null = null;    const xpResult = this.xp.checkDailyCap(userState.todayXP, 'card_review');    // Calculate XP  } {    comboUpdate: { newCombo: number; comboLost: boolean };    newMetaLearningUnlocks: MetaLearningUnlock[];    newAchievements: Achievement[];    xpTransaction: XPTransaction | null;  ): {    }      metaLearningUnlocks: string[];      unlockedAchievements: AchievementId[];      stats: UserLearningStats;      todayXP: number;      streakDays: number;      currentCombo: number;    userState: {    },      confidenceBefore?: number;      responseTimeMs: number;      cardDifficulty: number;      rating: Rating;    review: {  processReview(   */   * Process a card review and return all gamification updates  /**    }    this.metaLearning = new MetaLearningEngine(options?.metaLearningUnlocks);    this.leaderboards = new LeaderboardEngine();    this.challenges = new ChallengeEngine();    this.calibration = new CalibrationEngine();    this.skillTrees = new SkillTreeEngine(options?.skillTrees);    this.streaks = new StreakEngine();    this.achievements = new AchievementEngine();    this.xp = new XPEngine();  }) {    metaLearningUnlocks?: ReadonlyArray<MetaLearningUnlock>;    skillTrees?: ReadonlyArray<SkillTree>;  constructor(options?: {    public readonly metaLearning: MetaLearningEngine;  public readonly leaderboards: LeaderboardEngine;  public readonly challenges: ChallengeEngine;  public readonly calibration: CalibrationEngine;  public readonly skillTrees: SkillTreeEngine;  public readonly streaks: StreakEngine;  public readonly achievements: AchievementEngine;  public readonly xp: XPEngine;export class GamificationManager { */ * Central gamification system coordinator/**// =============================================================================// GAMIFICATION MANAGER// =============================================================================}  }    }));      isUnlocked: existingUnlocks.includes(unlock.id),      ...unlock,    return Array.from(this.unlocks.values()).map(unlock => ({  getAllUnlocks(existingUnlocks: string[]): Array<MetaLearningUnlock & { isUnlocked: boolean }> {   */   * Get all unlocks with their requirements and status  /**    }    }        return false;      default:              return stats.currentStreak >= threshold;      case 'streak_days':              return stats.masteredCards >= threshold;      case 'mastered_cards':              return (stats.level || 1) >= threshold;      case 'level':              return stats.totalReviews >= threshold;      case 'reviews_count':              return (stats.calibrationScore || 0) >= threshold;      case 'calibration_score':    switch (type) {        const { type, threshold } = unlock.requirement;  ): boolean {    stats: UserLearningStats & { calibrationScore?: number; level?: number }    unlock: MetaLearningUnlock,  private checkRequirement(    }    return newUnlocks;        }      }        });          unlockedAt: new Date(),          ...unlock,        newUnlocks.push({      if (this.checkRequirement(unlock, stats)) {            if (existingUnlocks.includes(id)) continue;    for (const [id, unlock] of this.unlocks) {        const newUnlocks: MetaLearningUnlock[] = [];  ): MetaLearningUnlock[] {    existingUnlocks: string[]    },      level?: number;      calibrationScore?: number;    stats: UserLearningStats & {  checkUnlocks(   */   * Check which meta-learning features should be unlocked  /**    }    this.unlocks = new Map(unlocks.map(u => [u.id, { ...u }]));  constructor(unlocks: ReadonlyArray<MetaLearningUnlock> = META_LEARNING_UNLOCKS) {    private unlocks: Map<string, MetaLearningUnlock>;export class MetaLearningEngine { */ * Meta-learning unlock manager/**];  },    unlockedAt: null,    },      threshold: 30,      type: 'streak_days',    requirement: {    description: 'AI-optimized session planning based on mental fatigue',    name: 'Cognitive Load Balancing',    id: 'cognitive_load_balancing',  {  },    unlockedAt: null,    },      threshold: 500,      type: 'mastered_cards',    requirement: {    description: 'Enable detection and prevention of memory interference',    name: 'Interference Modeling',    id: 'interference_modeling',  {  },    unlockedAt: null,    },      threshold: 0.85,      type: 'calibration_score',    requirement: {    description: 'Fine-tune algorithm parameters based on your learning patterns',    name: 'Parameter Tuning',    id: 'parameter_tuning',  {  },    unlockedAt: null,    },      threshold: 10,      type: 'level',    requirement: {    description: 'Access detailed memory analysis and prediction models',    name: 'Advanced Statistics',    id: 'advanced_statistics',  {  },    unlockedAt: null,    },      threshold: 1000,      type: 'reviews_count',    requirement: {    description: 'Choose between FSRS, HLR, or SM-2 scheduling algorithms',    name: 'Scheduler Selection',    id: 'scheduler_selection',  {  },    unlockedAt: null,    },      threshold: 0.7, // 70% calibration accuracy      type: 'calibration_score',    requirement: {    description: 'Manually adjust review intervals for individual cards',    name: 'Custom Intervals',    id: 'custom_intervals',  {export const META_LEARNING_UNLOCKS: ReadonlyArray<MetaLearningUnlock> = [ */ * Meta-learning features that unlock as users demonstrate proficiency/**// =============================================================================// META-LEARNING UNLOCKS// =============================================================================}  }    };      tier: this.determineTier(100 - (rank / 100)), // Approximate percentile      change: 0,      previousRank: null, // Would need historical data      score,      rank,      avatarUrl: user.avatarUrl || null,      displayName: user.displayName,      userId: user.id,    return {        const score = this.calculateRankingScore(stats, leaderboardType);  ): LeaderboardEntry {    leaderboardType: LeaderboardType    rank: number,    stats: UserLearningStats,    user: Pick<User, 'id' | 'displayName' | 'avatarUrl'>,  createEntry(   */   * Create leaderboard entry  /**    }    return 'bronze';    if (percentile >= 50) return 'silver';    if (percentile >= 80) return 'gold';    if (percentile >= 95) return 'platinum';    if (percentile >= 99) return 'diamond';  determineTier(percentile: number): 'bronze' | 'silver' | 'gold' | 'platinum' | 'diamond' {   */   * Determine leaderboard tier based on percentile  /**    }    }        return 0;      default:              return stats.totalReviews;      case 'reviews':              return Math.round(stats.averageAccuracy * 1000);        // Scale accuracy to a reasonable point value      case 'accuracy':              return stats.masteredCards;      case 'mastery':              return stats.currentStreak;      case 'streak':              return stats.totalXP;      case 'xp':    switch (leaderboardType) {  ): number {    leaderboardType: LeaderboardType    stats: UserLearningStats,  calculateRankingScore(   */   * Calculate leaderboard ranking score  /**export class LeaderboardEngine { */ * Leaderboard management/**// =============================================================================// LEADERBOARD SYSTEM// =============================================================================}  }    };      isComplete: percentComplete >= 100,      percentComplete,      targetValue: requirements.target,      currentValue: progress,      challengeId: challenge.id,    return {        const percentComplete = Math.min(100, (progress / requirements.target) * 100);        }        break;        }          progress += 1;        if (event.type === 'session_complete') {      case 'streak':              break;        }          progress = event.responseTime;        if (event.responseTime !== undefined) {      case 'speed':              break;        }          progress = event.accuracy;        if (event.accuracy !== undefined) {      case 'accuracy':              break;        progress += event.reviewCount || 1;      case 'reviews':    switch (requirements.type) {        let progress = requirements.current || 0;    const requirements = challenge.requirements as any;  ): ChallengeProgress {    }      reviewCount?: number;      responseTime?: number;      accuracy?: number;      type: 'review' | 'session_complete';    event: {    challenge: Challenge,  updateProgress(   */   * Update challenge progress  /**    }    };      isComplete: false,      endDate: endOfWeek,      startDate: now,      },        unlocks: [],        badge: 'weekly_warrior',        xp: Math.round(500 * difficultyMultiplier),      rewards: {      },        current: 0,        target: 7,        type: 'streak',      requirements: {      difficulty: 'hard',      type: 'weekly',      description: 'Complete review goals every day this week',      name: 'Weekly Warrior',      id: `weekly_${now.toISOString().split('T')[0]}` as ChallengeId,    return {        const difficultyMultiplier = 1 + (userLevel * 0.1);        endOfWeek.setHours(23, 59, 59, 999);    endOfWeek.setDate(endOfWeek.getDate() + (7 - endOfWeek.getDay()));    const endOfWeek = new Date(now);    const now = new Date();  generateWeeklyChallenge(userStats: UserLearningStats, userLevel: number): Challenge {   */   * Generate weekly challenge  /**    }    return challenges;        }      });        isComplete: false,        endDate: endOfDay,        startDate: now,        },          unlocks: [],          badge: null,          xp: Math.round(200 * difficultyMultiplier),        rewards: {        },          current: 0,          minimumReviews: 20,          target: 5000, // 5 seconds in ms          type: 'speed',        requirements: {        difficulty: 'hard',        type: 'daily',        description: 'Complete 20 reviews with average response under 5 seconds',        name: 'Quick Thinking',        id: `daily_speed_${now.toISOString().split('T')[0]}` as ChallengeId,      challenges.push({    if (userLevel >= 10) {    // Speed challenge        }      });        isComplete: false,        endDate: endOfDay,        startDate: now,        },          unlocks: [],          badge: null,          xp: Math.round(150 * difficultyMultiplier),        rewards: {        },          current: 0,          minimumReviews: 15,          target: 0.9,          type: 'accuracy',        requirements: {        difficulty: 'medium',        type: 'daily',        description: 'Achieve 90% accuracy on at least 15 reviews',        name: 'Precision Practice',        id: `daily_accuracy_${now.toISOString().split('T')[0]}` as ChallengeId,      challenges.push({    if (userLevel >= 5) {    // Accuracy challenge        });      isComplete: false,      endDate: endOfDay,      startDate: now,      },        unlocks: [],        badge: null,        xp: Math.round(100 * difficultyMultiplier),      rewards: {      },        current: 0,        target: Math.round(20 * difficultyMultiplier),        type: 'reviews',      requirements: {      difficulty: 'easy',      type: 'daily',      description: 'Complete your daily reviews',      name: 'Daily Dedication',      id: `daily_reviews_${now.toISOString().split('T')[0]}` as ChallengeId,    challenges.push({    // Standard daily challenge: Review cards        const difficultyMultiplier = 1 + (userLevel * 0.1);    // Scale difficulty with level        endOfDay.setHours(23, 59, 59, 999);    const endOfDay = new Date(now);    const now = new Date();    const challenges: Challenge[] = [];  generateDailyChallenges(userStats: UserLearningStats, userLevel: number): Challenge[] {   */   * Generate daily challenges based on user stats  /**export class ChallengeEngine { */ * Challenge definitions and management/**// =============================================================================// CHALLENGE SYSTEM// =============================================================================}  }    };      lastCalculated: new Date(),      factors,      trend,      score: Math.round(score * 100),    return {        }      });        description: 'Your memories have good long-term stability.',        impact: 'positive',        name: 'Stable Memory',      factors.push({    if (normalizedStability > 0.3) {        }      });        description: 'Over half your cards are mastered. Great progress!',        impact: 'positive',        name: 'Strong Mastery',      factors.push({    if (stats.masteredRatio > 0.5) {        }      });        description: 'Review patterns are irregular. Try to study at consistent times.',        impact: 'negative',        name: 'Inconsistent Reviews',      factors.push({    if (stats.reviewConsistency < 0.7) {        }      });        description: 'Your recall rate is below 80%. Consider reviewing more frequently.',        impact: 'negative',        name: 'Low Retention',      factors.push({    if (stats.retentionRate < 0.8) {        const factors: MemoryIntegrityScore['factors'] = [];    // Identify factors        const trend: 'improving' | 'stable' | 'declining' = 'stable'; // Would need historical data    // Determine trend based on recent vs historical          weights.variance * varianceScore;      weights.stability * normalizedStability +      weights.mastery * stats.masteredRatio +      weights.consistency * stats.reviewConsistency +      weights.retention * stats.retentionRate +    const score =         const varianceScore = 1 - Math.min(stats.recallVariance, 1);    // Variance is bad, so invert it        const normalizedStability = Math.min(stats.avgStability / 365, 1);    // Normalize stability (assuming max stability of ~365 days)        };      variance: 0.1,      stability: 0.2,      mastery: 0.2,      consistency: 0.2,      retention: 0.3,    const weights = {    // Weighted combination of factors  }): MemoryIntegrityScore {    recallVariance: number; // How consistent recall is across sessions    avgStability: number; // Average FSRS stability    masteredRatio: number; // 0-1 (mastered cards / total cards)    reviewConsistency: number; // 0-1 (how regularly reviews are done)    retentionRate: number; // 0-1  calculateMemoryIntegrity(stats: {   */   * Aggregate measure of memory system health   * Calculate Memory Integrity Score  /**    }    return '80-100';    if (confidence < 0.8) return '60-80';    if (confidence < 0.6) return '40-60';    if (confidence < 0.4) return '20-40';    if (confidence < 0.2) return '0-20';  private getBinKey(confidence: number): string {    }    };      breakdown: bins,      sampleSize: n,      underconfidence: Math.round((underconfidenceSum / n) * 100) / 100,      overconfidence: Math.round((overconfidenceSum / n) * 100) / 100,      score: Math.round(calibrationScore * 100) / 100,    return {        const calibrationScore = 1 - brierScore;    // Perfect calibration = 0 Brier = 1 score    // Convert Brier score to calibration score (1 - Brier gives 0-1 where 1 is best)        const brierScore = brierSum / n;    const n = reviews.length;        }      }        bin.avgConfidence /= bin.total;      if (bin.total > 0) {    for (const bin of Object.values(bins)) {    // Normalize bin averages        }      bins[binKey].avgConfidence += predicted;      bins[binKey].correct += actual;      bins[binKey].total++;      const binKey = this.getBinKey(predicted);      // Categorize into bins            }        underconfidenceSum += Math.abs(error);      } else {        overconfidenceSum += error;      if (error > 0) {            brierSum += Math.pow(error, 2);            const error = predicted - actual;      const actual = review.recalled ? 1 : 0;      const predicted = review.confidenceBefore;    for (const review of reviews) {        };      '80-100': { total: 0, correct: 0, avgConfidence: 0 },      '60-80': { total: 0, correct: 0, avgConfidence: 0 },      '40-60': { total: 0, correct: 0, avgConfidence: 0 },      '20-40': { total: 0, correct: 0, avgConfidence: 0 },      '0-20': { total: 0, correct: 0, avgConfidence: 0 },    const bins: Record<string, { total: number; correct: number; avgConfidence: number }> = {    // Breakdown by confidence bins (0-20%, 20-40%, etc.)        let underconfidenceSum = 0;    let overconfidenceSum = 0;    let brierSum = 0;    // Brier score: mean squared error between predictions and outcomes        }      };        breakdown: {},        sampleSize: 0,        underconfidence: 0,        overconfidence: 0,        score: 0.5,      return {    if (reviews.length === 0) {  ): CalibrationScore {    }>      cardDifficulty: number;      recalled: boolean;      confidenceBefore: number; // 0-1, user's predicted recall probability    reviews: Array<{  calculateCalibrationScore(   */   * Calculate calibration score from confidence ratings and outcomes  /**export class CalibrationEngine { */ * Based on Brier score and overconfidence/underconfidence metrics * Calibration score measures how well a user estimates their own knowledge/**// =============================================================================// CALIBRATION SCORING// =============================================================================}  }    };      })),        level: progressMap.get(node.id) || 0,        ...node,      nodes: tree.nodes.map(node => ({      ...tree,    return {        const progressMap = new Map(userProgress.map(p => [p.nodeId, p.level]));        if (!tree) return null;    const tree = this.skillTrees.get(treeId);  ): SkillTree | null {    userProgress: Array<{ nodeId: SkillNodeId; level: number }>    treeId: string,  getTreeWithProgress(   */   * Get skill tree with progress information  /**    }    return effects;        }      }        });          source: `${tree.name} - ${node.name} (Lv${skill.level})`,          value: scaledValue,          ...effect,        effects.push({                  : effect.value;          ? effect.value * skill.level        const scaledValue = typeof effect.value === 'number'        // Scale effect by level for numeric values      for (const effect of node.effects) {            if (!node || skill.level === 0) continue;      const node = tree.nodes.find(n => n.id === skill.nodeId);            if (!tree) continue;      const tree = this.skillTrees.get(skill.treeId);    for (const skill of unlockedSkills) {        const effects: Array<{ type: string; value: number | string; source: string }> = [];  }> {    source: string;    value: number | string;    type: string;  getActiveEffects(unlockedSkills: Array<{ treeId: string; nodeId: SkillNodeId; level: number }>): Array<{   */   * Get all active effects from unlocked skills  /**    }    };      effects: node.effects,      xpSpent,      success: true,    return {        node.unlockedAt = node.unlockedAt || new Date();    node.level++;    const xpSpent = node.xpRequired[node.level] || 0;        const node = tree.nodes.find(n => n.id === nodeId)!;    const tree = this.skillTrees.get(treeId)!;        }      return { success: false, xpSpent: 0, effects: [] };    if (!check.canUpgrade) {    const check = this.canUpgradeNode(treeId, nodeId, userXP, unlockedNodes);  ): { success: boolean; xpSpent: number; effects: SkillNode['effects'] } {    unlockedNodes: SkillNodeId[]    userXP: number,    nodeId: SkillNodeId,    treeId: string,  upgradeNode(   */   * Upgrade a skill node  /**    }    return { canUpgrade: true };        }      return { canUpgrade: false, reason: `Requires ${xpRequired} XP (you have ${userXP})` };    if (userXP < xpRequired) {    const xpRequired = node.xpRequired[node.level] || 0;    // Check XP requirement        }      }        return { canUpgrade: false, reason: `Requires ${prereq} to be unlocked first` };      if (!prereqNode || prereqNode.level === 0) {      const prereqNode = tree.nodes.find(n => n.id === prereq);    for (const prereq of node.prerequisites) {    // Check prerequisites        }      return { canUpgrade: false, reason: 'Already at max level' };    if (node.level >= node.maxLevel) {    // Check max level        }      return { canUpgrade: false, reason: 'Skill node not found' };    if (!node) {    const node = tree.nodes.find(n => n.id === nodeId);        }      return { canUpgrade: false, reason: 'Skill tree not found' };    if (!tree) {    const tree = this.skillTrees.get(treeId);  ): { canUpgrade: boolean; reason?: string } {    unlockedNodes: SkillNodeId[]    userXP: number,    nodeId: SkillNodeId,    treeId: string,  canUpgradeNode(   */   * Check if a skill node can be upgraded  /**    }    this.skillTrees = new Map(trees.map(t => [t.id, { ...t }]));  constructor(trees: ReadonlyArray<SkillTree> = DEFAULT_SKILL_TREES) {    private skillTrees: Map<string, SkillTree>;export class SkillTreeEngine { */ * Skill tree progression engine/**];  },    iconUrl: '/skill-trees/efficiency.svg',    totalXPRequired: 9800,    ],      },        unlockedAt: null,        iconUrl: '/skills/optimization.svg',        ],          { type: 'feature_unlock', value: 'ai_session_planning' },        effects: [        prerequisites: ['deep_work' as SkillNodeId],        xpRequired: [800, 1600, 3200],        maxLevel: 3,        level: 0,        description: 'AI-powered session planning',        name: 'Review Optimization',        id: 'review_optimization' as SkillNodeId,      {      },        unlockedAt: null,        iconUrl: '/skills/deep-work.svg',        ],          { type: 'session_bonus', value: 0.1 },        effects: [        prerequisites: ['pomodoro' as SkillNodeId],        xpRequired: [500, 1000, 2000],        maxLevel: 3,        level: 0,        description: 'Extended focus sessions',        name: 'Deep Work',        id: 'deep_work' as SkillNodeId,      {      },        unlockedAt: null,        iconUrl: '/skills/pomodoro.svg',        ],          { type: 'feature_unlock', value: 'pomodoro_timer' },        effects: [        prerequisites: [],        xpRequired: [200, 500],        maxLevel: 2,        level: 0,        description: 'Master focused study sessions',        name: 'Pomodoro Technique',        id: 'pomodoro' as SkillNodeId,      {    nodes: [    category: 'productivity',    description: 'Maximize your learning per minute',    name: 'Study Efficiency',    id: 'study_efficiency',  {  },    iconUrl: '/skill-trees/memory.svg',    totalXPRequired: 9000,    ],      },        unlockedAt: null,        iconUrl: '/skills/visualization.svg',        ],          { type: 'card_type_unlock', value: 'image_occlusion_advanced' },        effects: [        prerequisites: ['memory_palace' as SkillNodeId],        xpRequired: [600, 1200, 2400],        maxLevel: 3,        level: 0,        description: 'Create vivid mental images',        name: 'Visualization',        id: 'visualization' as SkillNodeId,      {      },        unlockedAt: null,        iconUrl: '/skills/chunking.svg',        ],          { type: 'card_limit_increase', value: 50 },        effects: [        prerequisites: ['memory_palace' as SkillNodeId],        xpRequired: [400, 900],        maxLevel: 2,        level: 0,        description: 'Group information for easier recall',        name: 'Chunking',        id: 'chunking' as SkillNodeId,      {      },        unlockedAt: null,        iconUrl: '/skills/memory-palace.svg',        ],          { type: 'feature_unlock', value: 'memory_palace_cards' },        effects: [        prerequisites: [],        xpRequired: [500, 1000, 2000],        maxLevel: 3,        level: 0,        description: 'Unlock the method of loci',        name: 'Memory Palace',        id: 'memory_palace' as SkillNodeId,      {    nodes: [    category: 'cognitive',    description: 'Advanced memory enhancement techniques',    name: 'Memory Mastery',    id: 'memory_mastery',  {  },    iconUrl: '/skill-trees/fundamentals.svg',    totalXPRequired: 5050,    ],      },        unlockedAt: null,        iconUrl: '/skills/elaboration.svg',        ],          { type: 'card_type_unlock', value: 'concept_graph' },        effects: [        prerequisites: ['active_recall' as SkillNodeId],        xpRequired: [200, 500, 1000],        maxLevel: 3,        level: 0,        description: 'Connect new knowledge to existing',        name: 'Elaboration',        id: 'elaboration' as SkillNodeId,      {      },        unlockedAt: null,        iconUrl: '/skills/interleaving.svg',        ],          { type: 'feature_unlock', value: 'interleaved_practice' },        effects: [        prerequisites: ['spaced_repetition' as SkillNodeId],        xpRequired: [300, 800],        maxLevel: 2,        level: 0,        description: 'Mix different topics for better learning',        name: 'Interleaving',        id: 'interleaving' as SkillNodeId,      {      },        unlockedAt: null,        iconUrl: '/skills/spaced-repetition.svg',        ],          { type: 'retention_bonus', value: 0.05 },        effects: [        prerequisites: ['active_recall' as SkillNodeId],        xpRequired: [150, 400, 900],        maxLevel: 3,        level: 0,        description: 'Optimize your review intervals',        name: 'Spaced Repetition',        id: 'spaced_repetition' as SkillNodeId,      {      },        unlockedAt: null,        iconUrl: '/skills/active-recall.svg',        ],          { type: 'xp_bonus', value: 0.05 },        effects: [        prerequisites: [],        xpRequired: [100, 300, 700],        maxLevel: 3,        level: 1,        description: 'Unlock the power of retrieval practice',        name: 'Active Recall',        id: 'active_recall' as SkillNodeId,      {    nodes: [    category: 'cognitive',    description: 'Master the basics of effective learning',    name: 'Learning Fundamentals',    id: 'learning_fundamentals',  {export const DEFAULT_SKILL_TREES: ReadonlyArray<SkillTree> = [ */ * Default skill tree definitions/**// =============================================================================// SKILL TREE SYSTEM// =============================================================================}  }    };      nextRefill,      canUse: available > 0,      available,    return {        }      nextRefill.setDate(nextRefill.getDate() + 7);      nextRefill = new Date(user.lastFreezeUsed);    if (available < maxFreezes && user.lastFreezeUsed) {    let nextRefill: Date | null = null;    // Freezes refill every 7 days of streak        const available = Math.min(user.streakFreezeCount, maxFreezes);  ): { available: number; canUse: boolean; nextRefill: Date | null } {    maxFreezes: number = 2    user: { streakFreezeCount: number; lastFreezeUsed: Date | null },  getStreakFreezeStatus(   */   * Calculate streak freeze availability  /**    }    };      hoursRemaining: Math.max(0, hoursRemaining),      atRisk: hoursRemaining > 0 && hoursRemaining <= 6,    return {        const hoursRemaining = (deadline.getTime() - currentDate.getTime()) / (1000 * 60 * 60);        deadline.setHours(this.gracePeriodHours, 0, 0, 0);    deadline.setDate(deadline.getDate() + 1);    const deadline = new Date(last);    const last = new Date(lastActivityDate);  ): { atRisk: boolean; hoursRemaining: number } {    currentDate: Date = new Date()    lastActivityDate: Date,  isStreakAtRisk(   */   * Check if streak is at risk (close to breaking)  /**    }    }      };        // Keep longest streak record        lastActivityDate: currentDate,        currentCount: 1,        ...currentStreak,      return {      // Streak broken - reset            }        };          ),            currentStreak.currentCount + 1            currentStreak.longestStreak,          longestStreak: Math.max(          lastActivityDate: currentDate,          currentCount: currentStreak.currentCount + 1,          ...currentStreak,        return {        // Within grace period - continue streak      if (currentDate <= graceDeadline) {            graceDeadline.setHours(this.gracePeriodHours, 0, 0, 0);      graceDeadline.setDate(graceDeadline.getDate() + 1);      const graceDeadline = new Date(lastDate);      // Check grace period (within gracePeriodHours of previous day)      // Streak broken    } else {      };        ),          currentStreak.currentCount + 1          currentStreak.longestStreak,        longestStreak: Math.max(        lastActivityDate: currentDate,        currentCount: currentStreak.currentCount + 1,        ...currentStreak,      return {      // Consecutive day - increment streak    } else if (diffDays === 1) {      return currentStreak;      // Same day - no change    if (diffDays === 0) {        const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24));    const diffMs = today.getTime() - lastDate.getTime();        today.setHours(0, 0, 0, 0);    lastDate.setHours(0, 0, 0, 0);    // Reset to start of day        const today = new Date(currentDate);    const lastDate = new Date(lastActivityDate);  ): Streak {    currentDate: Date = new Date()    lastActivityDate: Date,    currentStreak: Streak,  updateStreak(   */   * Update streak based on activity  /**    private readonly gracePeriodHours = 12; // Hours after midnight to maintain streakexport class StreakEngine { */ * Streak tracking and management/**// =============================================================================// STREAK SYSTEM// =============================================================================}  }    return grouped;        }      grouped[achievement.category].push(achievement);      }        grouped[achievement.category] = [];      if (!grouped[achievement.category]) {    for (const achievement of this.achievements.values()) {        const grouped: Record<string, Achievement[]> = {};  getAchievementsByCategory(): Record<string, Achievement[]> {   */   * Get all achievements grouped by category  /**    }    };      percentComplete: Math.min(100, (currentValue / condition.threshold) * 100),      targetValue: condition.threshold,      currentValue,      achievementId,    return {        }        currentValue = (stats as any)[condition.type] || 0;      default:        break;        currentValue = stats.masteredCards;      case 'mastered_cards':        break;        currentValue = stats.currentStreak;      case 'streak_days':        break;        currentValue = stats.totalReviews;      case 'reviews_count':    switch (condition.type) {        let currentValue = 0;    const { condition } = achievement;        }      throw new Error(`Achievement not found: ${achievementId}`);    if (!achievement) {    const achievement = this.achievements.get(achievementId);  getProgress(achievementId: AchievementId, stats: UserLearningStats): AchievementProgress {   */   * Calculate progress towards an achievement  /**    }    }        return false;      default:              return (stats as any).daysAway >= condition.threshold;      case 'comeback':              return (stats as any).morningReviews >= condition.threshold;      case 'morning_reviews':              return (stats as any).nightReviews >= condition.threshold;      case 'night_reviews':              return (stats as any).deckDownloads >= condition.threshold;      case 'deck_downloads':              return (stats as any).decksShared >= condition.threshold;      case 'decks_shared':              return (stats as any).cardsCreated >= condition.threshold;      case 'cards_created':              return (stats as any).decksCreated >= condition.threshold;      case 'decks_created':              return (stats as any).accuracyStreak >= condition.threshold;      case 'accuracy_streak':              return (stats as any).perfectSessions >= condition.threshold;      case 'perfect_session':              return stats.masteredCards >= condition.threshold;      case 'mastered_cards':              return stats.currentStreak >= condition.threshold;      case 'streak_days':              return stats.totalReviews >= condition.threshold;      case 'reviews_count':    switch (condition.type) {        const { condition } = achievement;  private checkCondition(achievement: Achievement, stats: UserLearningStats): boolean {   */   * Check if a specific achievement condition is met  /**    }    return newUnlocks;        }      }        });          unlockedAt: new Date(),          ...achievement,        newUnlocks.push({      if (this.checkCondition(achievement, stats)) {      // Check condition            if (existingAchievements.includes(id)) continue;      // Skip already unlocked    for (const [id, achievement] of this.achievements) {        const newUnlocks: Achievement[] = [];  ): Achievement[] {    existingAchievements: AchievementId[]    stats: UserLearningStats,  checkUnlocks(   */   * Check if any achievements should be unlocked based on stats  /**    }    );      ACHIEVEMENTS.map(a => [a.id, { ...a }])    this.achievements = new Map(  constructor() {    private achievements: Map<AchievementId, Achievement>;export class AchievementEngine { */ * Achievement tracking engine/**] as const;  },    unlockedAt: null,    condition: { type: 'comeback', threshold: 30 },    xpReward: 300,    iconUrl: '/achievements/comeback-kid.svg',    rarity: 'rare',    category: 'special',    description: 'Return after 30+ days away and complete a session',    name: 'Comeback Kid',    id: 'comeback_kid' as AchievementId,  {  },    unlockedAt: null,    condition: { type: 'morning_reviews', threshold: 100 },    xpReward: 200,    iconUrl: '/achievements/early-bird.svg',    rarity: 'rare',    category: 'special',    description: 'Complete 100 reviews between 5 AM and 7 AM',    name: 'Early Bird',    id: 'early_bird' as AchievementId,  {  },    unlockedAt: null,    condition: { type: 'night_reviews', threshold: 100 },    xpReward: 200,    iconUrl: '/achievements/night-owl.svg',    rarity: 'rare',    category: 'special',    description: 'Complete 100 reviews between midnight and 5 AM',    name: 'Night Owl',    id: 'night_owl' as AchievementId,  {  // Special achievements    },    unlockedAt: null,    condition: { type: 'deck_downloads', threshold: 100 },    xpReward: 1500,    iconUrl: '/achievements/helpful-curator.svg',    rarity: 'epic',    category: 'social',    description: 'Have your shared deck downloaded 100 times',    name: 'Helpful Curator',    id: 'helpful_curator' as AchievementId,  {  },    unlockedAt: null,    condition: { type: 'decks_shared', threshold: 1 },    xpReward: 100,    iconUrl: '/achievements/first-share.svg',    rarity: 'common',    category: 'social',    description: 'Share your first deck with the community',    name: 'Sharing is Caring',    id: 'first_share' as AchievementId,  {  // Social achievements    },    unlockedAt: null,    condition: { type: 'cards_created', threshold: 100 },    xpReward: 300,    iconUrl: '/achievements/content-creator.svg',    rarity: 'rare',    category: 'creation',    description: 'Create 100 cards',    name: 'Content Creator',    id: 'hundred_cards_created' as AchievementId,  {  },    unlockedAt: null,    condition: { type: 'decks_created', threshold: 1 },    xpReward: 50,    iconUrl: '/achievements/first-deck.svg',    rarity: 'common',    category: 'creation',    description: 'Create your first deck',    name: 'Deck Creator',    id: 'first_deck' as AchievementId,  {  // Creation achievements    },    unlockedAt: null,    condition: { type: 'accuracy_streak', threshold: 7 },    xpReward: 1000,    iconUrl: '/achievements/perfect-week.svg',    rarity: 'epic',    category: 'accuracy',    description: 'Maintain 90%+ accuracy for 7 consecutive days',    name: 'Flawless Week',    id: 'perfect_week' as AchievementId,  {  },    unlockedAt: null,    condition: { type: 'perfect_session', threshold: 1 },    xpReward: 250,    iconUrl: '/achievements/perfect-session.svg',    rarity: 'rare',    category: 'accuracy',    description: 'Complete a study session with 100% accuracy (min 20 cards)',    name: 'Perfect Session',    id: 'perfect_session' as AchievementId,  {  // Accuracy achievements    },    unlockedAt: null,    condition: { type: 'mastered_cards', threshold: 1000 },    xpReward: 2500,    iconUrl: '/achievements/thousand-mastery.svg',    rarity: 'epic',    category: 'mastery',    description: 'Master 1,000 cards',    name: 'Master Scholar',    id: 'thousand_mastery' as AchievementId,  {  },    unlockedAt: null,    condition: { type: 'mastered_cards', threshold: 100 },    xpReward: 500,    iconUrl: '/achievements/hundred-mastery.svg',    rarity: 'rare',    category: 'mastery',    description: 'Master 100 cards',    name: 'Knowledge Builder',    id: 'hundred_mastery' as AchievementId,  {  },    unlockedAt: null,    condition: { type: 'mastered_cards', threshold: 1 },    xpReward: 75,    iconUrl: '/achievements/first-mastery.svg',    rarity: 'common',    category: 'mastery',    description: 'Master your first card (95%+ recall)',    name: 'First Mastery',    id: 'first_mastery' as AchievementId,  {  // Mastery achievements    },    unlockedAt: null,    condition: { type: 'streak_days', threshold: 365 },    xpReward: 10000,    iconUrl: '/achievements/year-streak.svg',    rarity: 'legendary',    category: 'streak',    description: 'Maintain a 365-day streak',    name: 'The Unstoppable',    id: 'year_streak' as AchievementId,  {  },    unlockedAt: null,    condition: { type: 'streak_days', threshold: 100 },    xpReward: 2000,    iconUrl: '/achievements/centurion.svg',    rarity: 'epic',    category: 'streak',    description: 'Maintain a 100-day streak',    name: 'Centurion',    id: 'hundred_day_streak' as AchievementId,  {  },    unlockedAt: null,    condition: { type: 'streak_days', threshold: 30 },    xpReward: 500,    iconUrl: '/achievements/month-streak.svg',    rarity: 'rare',    category: 'streak',    description: 'Maintain a 30-day streak',    name: 'Monthly Commitment',    id: 'month_streak' as AchievementId,  {  },    unlockedAt: null,    condition: { type: 'streak_days', threshold: 7 },    xpReward: 100,    iconUrl: '/achievements/week-streak.svg',    rarity: 'common',    category: 'streak',    description: 'Maintain a 7-day streak',    name: 'One Week Wonder',    id: 'week_streak' as AchievementId,  {  // Streak achievements    },    unlockedAt: null,    condition: { type: 'reviews_count', threshold: 100000 },    xpReward: 10000,    iconUrl: '/achievements/polymath.svg',    rarity: 'legendary',    category: 'learning',    description: 'Complete 100,000 card reviews',    name: 'Polymath',    id: 'hundred_thousand_reviews' as AchievementId,  {  },    unlockedAt: null,    condition: { type: 'reviews_count', threshold: 10000 },    xpReward: 2000,    iconUrl: '/achievements/ten-thousand-reviews.svg',    rarity: 'epic',    category: 'learning',    description: 'Complete 10,000 card reviews',    name: 'Knowledge Seeker',    id: 'ten_thousand_reviews' as AchievementId,  {  },    unlockedAt: null,    condition: { type: 'reviews_count', threshold: 1000 },    xpReward: 500,    iconUrl: '/achievements/thousand-reviews.svg',    rarity: 'rare',    category: 'learning',    description: 'Complete 1,000 card reviews',    name: 'Dedicated Learner',    id: 'thousand_reviews' as AchievementId,  {  },    unlockedAt: null,    condition: { type: 'reviews_count', threshold: 100 },    xpReward: 100,    iconUrl: '/achievements/hundred-reviews.svg',    rarity: 'common',    category: 'learning',    description: 'Complete 100 card reviews',    name: 'Getting Started',    id: 'hundred_reviews' as AchievementId,  {  },    unlockedAt: null,    condition: { type: 'reviews_count', threshold: 1 },    xpReward: 50,    iconUrl: '/achievements/first-steps.svg',    rarity: 'common',    category: 'learning',    description: 'Complete your first card review',    name: 'First Steps',    id: 'first_review' as AchievementId,  {  // Learning milestonesexport const ACHIEVEMENTS: ReadonlyArray<Achievement> = [ */ * Achievement definitions with unlock conditions/**// =============================================================================// ACHIEVEMENT SYSTEM// =============================================================================}  }    };      remaining: Math.max(0, remaining),      allowed: remaining > 0,    return {        );      reviewCap      this.config.caps.dailyXP - todayXP,    const remaining = Math.min(    const reviewCap = source === 'card_review' ? this.config.caps.reviewXP : Infinity;  checkDailyCap(todayXP: number, source: XPSource): { allowed: boolean; remaining: number } {   */   * Check if daily cap has been reached  /**    }    return total;    }      total += Math.round(base * Math.pow(i, exponent));    for (let i = 1; i <= level; i++) {    let total = 0;    const { base, exponent } = this.config.levelCurve;  private xpForLevel(level: number): number {   */   * Calculate total XP required for a level  /**    }    };      nextLevelXP: nextXP - previousXP,      currentLevelXP: totalXP - previousXP,      level: Math.max(1, level),    return {        const nextXP = this.xpForLevel(level + 1);      : 0;      ? this.xpForLevel(level)    const previousXP = level > 1     level--; // Step back to actual level        }      xpRequired += Math.round(base * Math.pow(level, exponent));      level++;    while (xpRequired <= totalXP) {        let xpRequired = 0;    let level = 1;    // Approximation using integration    // Solve for level: totalXP = sum(base * i^exponent) for i = 1 to level        const { base, exponent } = this.config.levelCurve;  calculateLevel(totalXP: number): { level: number; currentLevelXP: number; nextLevelXP: number } {   */   * Calculate level from total XP  /**    }    };      timestamp: new Date(),      },        bonuses,        streakDays,        combo: currentCombo,        responseTimeMs,        cardDifficulty,        rating,      details: {      source: 'card_review',      amount: xp,      userId: '' as UserId, // Set by caller      id: crypto.randomUUID(),    return {        }      bonuses.push({ source: 'streak', amount: bonus });      xp += bonus;      const bonus = Math.round(xp * streakMultiplier);      );        0.7 // Max 70% bonus (7 days)        streakDays * this.config.multipliers.consistencyBonus,      const streakMultiplier = Math.min(    if (streakDays > 0) {    // Streak consistency bonus        }      bonuses.push({ source: 'combo', amount: bonus });      xp += bonus;      const bonus = Math.round(xp * (comboMultiplier - 1));      );        2 // Max 2x multiplier        1 + (currentCombo * this.config.multipliers.comboMultiplier),      const comboMultiplier = Math.min(    if (currentCombo > 1) {    // Combo multiplier        }      bonuses.push({ source: 'speed', amount: bonus });      xp += bonus;      const bonus = Math.round(xp * speedFactor * this.config.multipliers.speedBonus);      const speedFactor = 1 - (responseTimeMs / avgResponseTime);    if (responseTimeMs < avgResponseTime && rating >= 3) {    const avgResponseTime = 8000; // 8 seconds average    // Speed bonus for quick, accurate reviews        }      bonuses.push({ source: 'difficulty_mastery', amount: bonus });      xp += bonus;      const bonus = Math.round(xp * this.config.multipliers.difficultyBonus);    if (cardDifficulty > 0.6 && rating >= 3) {    // Difficulty bonus for mastering hard cards        }      bonuses.push({ source: 'perfect_review', amount: bonus });      xp += bonus;      const bonus = this.config.base.perfectReview;    if (rating === 4) {    // Perfect review bonus (rated "Easy")        const bonuses: Array<{ source: string; amount: number }> = [];    let xp = this.config.base.cardReview;  ): XPTransaction {    streakDays: number    currentCombo: number,    responseTimeMs: number,    cardDifficulty: number,    rating: Rating,  calculateReviewXP(   */   * Calculate XP for a card review  /**    private config = XP_CONFIG;export class XPEngine { */ * XP calculation engine/**} as const;  },    bonusXP: 1000,    reviewXP: 2000, // Max from reviews alone    dailyXP: 5000,  caps: {  // Daily/weekly caps to prevent burnout    },    exponent: 1.5,    base: 100,  levelCurve: {  // Uses polynomial curve: XP = 100 * level^1.5  // Level progression (XP required per level)    },    comboMultiplier: 0.05, // +5% per combo step (max 2x)    perfectWeekBonus: 1.5, // 1.5x for perfect week    consistencyBonus: 0.1, // +10% per consecutive day (max 7x)    speedBonus: 0.2, // +20% for fast, accurate reviews    difficultyBonus: 0.5, // +50% for hard cards mastered  multipliers: {  // Multipliers    },    challengeComplete: 200,    streakMilestone: 100, // Per 7 days    dailyGoalComplete: 50,    achievementUnlock: 100,    deckCreation: 25,    cardCreation: 15,    perfectReview: 5, // Bonus for rating "Easy"    cardReview: 10,  base: {  // Base XP per activityexport const XP_CONFIG = { */ * XP multipliers and base values for different activities/**// =============================================================================// XP SYSTEM// =============================================================================import type { Rating, ReviewRecord } from './types/card.types';} from './types';  RewardType,  Reward,  ChallengeProgress,  ChallengeId,  Challenge,  Badge,  GamificationSettings,  MetaLearningUnlock,  MemoryIntegrityScore,  CalibrationScore,  LeaderboardType,  LeaderboardEntry,  SkillCategory,  SkillNodeId,  SkillNode,  SkillTree,  StreakType,  Streak,  AchievementProgress,  AchievementId,  Achievement,  XPSource,  XPTransaction,  UserLearningStats,  User,  UserId,import type {import { z } from 'zod';// - Variable ratio reinforcement: Random rewards increase engagement// - Progress principle: Small wins drive engagement// - Self-determination theory: Autonomy, competence, relatedness// - Flow theory (Csikszentmihalyi): Optimal challenge-skill balance// Research basis://// skill trees, calibration scoring, and meta-learning unlocks// Implements gamification mechanics including XP, achievements, streaks,// =============================================================================// =============================================================================
// Central export point for all shared types, algorithms, and utilities
// Used by both the API and mobile app packages
//
// Named after "Manthanein" (μανθάνειν) - Greek for "to learn"
// The root of words like "mathematics" and "polymath"

// =============================================================================
// TYPES
// =============================================================================
// All TypeScript interfaces and type definitions

export * from './types';

// =============================================================================
// ALGORITHMS
// =============================================================================
// Spaced repetition scheduling algorithms (FSRS, HLR, etc.)

export * from './algorithms';

// =============================================================================
// PLUGINS
// =============================================================================
// Plugin system for extensibility

export * from './plugins';

// =============================================================================
// GAMIFICATION
// =============================================================================
// XP, achievements, streaks, skill trees, and meta-learning

export * from './gamification';

// =============================================================================
// RE-EXPORTS FOR CONVENIENCE
// =============================================================================

// Most commonly used types
export type {
  // User types
  User,
  UserId,
  UserPreferences,
  UserLearningStats,
  
  // Card types
  Card,
  CardId,
  CardType,
  CardContent,
  CardState,
  CardSRSState,
  Rating,
  
  // Deck types
  Deck,
  DeckId,
  DeckSettings,
  DeckStats,
  StudySession,
  ReviewRecord,
  
  // Scheduler types
  SchedulerType,
  SchedulerConfig,
  SchedulingResult,
  SchedulingContext,
  
  // Plugin types
  PluginId,
  PluginManifest,
  PluginCategory,
  CardGenerationPlugin,
  SchedulingPlugin,
  
  // API types
  APIResponse,
  LoginResponse,
  CardDTO,
  DeckDTO,
} from './types';

// Most commonly used constants
export {
  RatingValues,
  DEFAULT_DECK_SETTINGS,
  DEFAULT_FSRS_CONFIG,
  DEFAULT_FSRS_WEIGHTS,
  DEFAULT_HLR_CONFIG,
  getDefaultSchedulerConfig,
  MASTERY_REQUIREMENTS,
  LEARNING_STRATEGIES,
} from './types';

// Most commonly used functions
export {
  createScheduler,
  createInitialSRSState,
  isCardDue,
  formatInterval,
} from './algorithms';
