/**
 * @noema/events - Event Factory
 *
 * Helper functions for creating events with proper structure.
 */

import type { CausationId, CorrelationId, Environment, EventId } from '@noema/types';
import type { AggregateId, AggregateType, EventType, IBaseEvent, IEventMetadata } from './types.js';

// ============================================================================
// Event Builder Options
// ============================================================================

/**
 * All options required to create an event.
 */
export interface ICreateEventOptions<TPayload> {
  /** Event ID (must be generated by caller) */
  eventId: EventId;

  /** Event type (e.g., "card.created") */
  eventType: EventType;

  /** Aggregate type (e.g., "Card") */
  aggregateType: AggregateType;

  /** Aggregate ID */
  aggregateId: AggregateId;

  /** Event payload */
  payload: TPayload;

  /** Schema version (defaults to 1) */
  version?: number;

  /** Event metadata */
  metadata: IEventMetadata;
}

/**
 * Context provided at event creation time.
 */
export interface IEventContext {
  /** Service name (e.g., "content-service") */
  serviceName: string;

  /** Service version (e.g., "1.0.0") */
  serviceVersion: string;

  /** Current environment */
  environment: Environment;
}

// ============================================================================
// Event Creation
// ============================================================================

/**
 * Create a new event with all required fields populated.
 */
export function createEvent<TPayload>(
  options: ICreateEventOptions<TPayload>
): IBaseEvent<TPayload> {
  const {
    eventId,
    eventType,
    aggregateType,
    aggregateId,
    payload,
    version = 1,
    metadata,
  } = options;

  return {
    eventId,
    eventType,
    aggregateType,
    aggregateId,
    version,
    timestamp: new Date().toISOString(),
    metadata,
    payload,
  };
}

// ============================================================================
// Event Builder (Fluent API)
// ============================================================================

/**
 * Fluent builder for creating events.
 */
export class EventBuilder<TPayload = unknown> {
  private _eventId?: EventId;
  private _eventType?: EventType;
  private _aggregateType?: AggregateType;
  private _aggregateId?: AggregateId;
  private _version = 1;
  private _payload?: TPayload;
  private _metadata: Partial<IEventMetadata> = {};

  /**
   * Set event ID (required).
   */
  id(eventId: EventId): this {
    this._eventId = eventId;
    return this;
  }

  /**
   * Set event type.
   */
  type(eventType: EventType): this {
    this._eventType = eventType;
    return this;
  }

  /**
   * Set aggregate info.
   */
  aggregate(type: AggregateType, id: AggregateId): this {
    this._aggregateType = type;
    this._aggregateId = id;
    return this;
  }

  /**
   * Set schema version.
   */
  schemaVersion(version: number): this {
    this._version = version;
    return this;
  }

  /**
   * Set event payload.
   */
  withPayload<P>(payload: P): EventBuilder<P> {
    const builder = this as unknown as EventBuilder<P>;
    builder._payload = payload;
    return builder;
  }

  /**
   * Set event metadata.
   */
  withMetadata(metadata: Partial<IEventMetadata>): this {
    this._metadata = { ...this._metadata, ...metadata };
    return this;
  }

  /**
   * Set service context.
   */
  fromService(name: string, version: string, environment: Environment): this {
    this._metadata.serviceName = name;
    this._metadata.serviceVersion = version;
    this._metadata.environment = environment;
    return this;
  }

  /**
   * Set tracing context.
   */
  withTracing(correlationId: CorrelationId, causationId?: CausationId | null): this {
    this._metadata.correlationId = correlationId;
    if (causationId !== undefined) {
      this._metadata.causationId = causationId;
    }
    return this;
  }

  /**
   * Build the event.
   */
  build(): IBaseEvent<TPayload> {
    if (this._eventId === undefined) throw new Error('Event ID is required');
    if (this._eventType === undefined) throw new Error('Event type is required');
    if (this._aggregateType === undefined) throw new Error('Aggregate type is required');
    if (this._aggregateId === undefined) throw new Error('Aggregate ID is required');
    if (this._payload === undefined) throw new Error('Payload is required');
    if (this._metadata.serviceName === undefined) throw new Error('Service name is required');
    if (this._metadata.serviceVersion === undefined) throw new Error('Service version is required');
    if (this._metadata.environment === undefined) throw new Error('Environment is required');
    if (this._metadata.correlationId === undefined) throw new Error('Correlation ID is required');

    const fullMetadata: IEventMetadata = {
      serviceName: this._metadata.serviceName,
      serviceVersion: this._metadata.serviceVersion,
      environment: this._metadata.environment,
      correlationId: this._metadata.correlationId,
      userId: this._metadata.userId ?? null,
      sessionId: this._metadata.sessionId ?? null,
      causationId: this._metadata.causationId ?? null,
      agentId: this._metadata.agentId ?? null,
      clientIp: this._metadata.clientIp ?? null,
      userAgent: this._metadata.userAgent ?? null,
      ...(this._metadata.additional !== undefined && {
        additional: this._metadata.additional,
      }),
    };

    return createEvent({
      eventId: this._eventId,
      eventType: this._eventType,
      aggregateType: this._aggregateType,
      aggregateId: this._aggregateId,
      payload: this._payload,
      version: this._version,
      metadata: fullMetadata,
    });
  }
}

/**
 * Start building an event.
 */
export function event(): EventBuilder {
  return new EventBuilder();
}

// ============================================================================
// Causation Chain Helper
// ============================================================================

/**
 * Create a child event that was caused by a parent event.
 */
export function createCausedEvent<TPayload>(
  parentEvent: IBaseEvent,
  options: {
    eventId: EventId;
    eventType: EventType;
    aggregateType: AggregateType;
    aggregateId: AggregateId;
    payload: TPayload;
    version?: number;
  }
): IBaseEvent<TPayload> {
  return createEvent({
    ...options,
    metadata: {
      serviceName: parentEvent.metadata.serviceName,
      serviceVersion: parentEvent.metadata.serviceVersion,
      environment: parentEvent.metadata.environment,
      correlationId: parentEvent.metadata.correlationId,
      causationId: parentEvent.eventId as unknown as CausationId,
      userId: parentEvent.metadata.userId ?? null,
      sessionId: parentEvent.metadata.sessionId ?? null,
      agentId: parentEvent.metadata.agentId ?? null,
      clientIp: parentEvent.metadata.clientIp ?? null,
      userAgent: parentEvent.metadata.userAgent ?? null,
      ...(parentEvent.metadata.additional !== undefined && {
        additional: parentEvent.metadata.additional,
      }),
    },
  });
}
