// =============================================================================
// LKGC FOUNDATION - Identity, Provenance, Privacy, and Sync
// =============================================================================
// Every entity, event, edge, state object, and proposal MUST support these
// foundational concerns. This file defines the base types that ALL other
// LKGC types inherit from.
// =============================================================================

// -----------------------------------------------------------------------------
// BRANDED TYPES - Type-safe identifiers
// -----------------------------------------------------------------------------

declare const __brand: unique symbol;
type Brand<T, B> = T & { readonly [__brand]: B };

/** Unique identifier for any LKGC entity */
export type EntityId = Brand<string, "EntityId">;

/** Unique identifier for a device */
export type DeviceId = Brand<string, "DeviceId">;

/** Unique identifier for a user */
export type UserId = Brand<string, "UserId">;

/** Unique identifier for a study session */
export type SessionId = Brand<string, "SessionId">;

/** Unique identifier for a node in the graph */
export type NodeId = Brand<string, "NodeId">;

/** Unique identifier for an edge in the graph */
export type EdgeId = Brand<string, "EdgeId">;

/** Unique identifier for an event */
export type EventId = Brand<string, "EventId">;

/** Unique identifier for a proposal */
export type ProposalId = Brand<string, "ProposalId">;

/** Unique identifier for a snapshot */
export type SnapshotId = Brand<string, "SnapshotId">;

/** Monotonically increasing local revision number */
export type RevisionNumber = Brand<number, "RevisionNumber">;

/** Confidence score in range [0, 1] */
export type Confidence = Brand<number, "Confidence">;

/** Probability in range [0, 1] */
export type Probability = Brand<number, "Probability">;

/** Unix timestamp in milliseconds */
export type Timestamp = Brand<number, "Timestamp">;

/** Duration in milliseconds */
export type Duration = Brand<number, "Duration">;

// -----------------------------------------------------------------------------
// PROVENANCE - Source and trust information
// -----------------------------------------------------------------------------

/**
 * Source of data or inference
 */
export type DataSource =
  | "user_action" // Direct user input
  | "import_parser" // Parsed from imported content
  | "ai_inference" // Inferred by AI model
  | "plugin" // Generated by plugin
  | "sync_merge" // Result of sync conflict resolution
  | "system"; // System-generated (e.g., defaults)

/**
 * Provenance information for any piece of data
 * Tracks where data came from and how trustworthy it is
 */
export interface Provenance {
  /** How this data was created */
  readonly source: DataSource;

  /** Identifier of the specific source (parser name, model ID, plugin ID) */
  readonly sourceId: string;

  /** Confidence score for inferred data [0..1], 1.0 for user-provided */
  readonly confidence: Confidence;

  /** When this data was created */
  readonly createdAt: Timestamp;

  /** When this data was last updated */
  readonly updatedAt: Timestamp;

  /** Device that created this data */
  readonly deviceId: DeviceId;

  /** App version that created this data */
  readonly appVersion: string;

  /** Schema version for forward/backward compatibility */
  readonly schemaVersion: number;

  /** Optional: User who created this (for multi-user scenarios) */
  readonly userId?: UserId;

  /** Optional: Parent provenance for derived data */
  readonly derivedFrom?: readonly EntityId[];
}

// -----------------------------------------------------------------------------
// PRIVACY & SCOPE - Data classification and consent
// -----------------------------------------------------------------------------

/**
 * Privacy level for data
 */
export type PrivacyLevel =
  | "private" // User-only, never shared
  | "shared" // Shareable with trusted parties
  | "public"; // Can be published

/**
 * Granular telemetry consent flags
 */
export interface TelemetryConsent {
  /** Allow aggregated event counts */
  readonly events: boolean;

  /** Allow text content (prompts, answers) */
  readonly text: boolean;

  /** Allow audio recordings */
  readonly audio: boolean;

  /** Allow performance metrics */
  readonly performance: boolean;

  /** Allow error reports */
  readonly errors: boolean;

  /** Allow usage patterns (session times, etc.) */
  readonly usagePatterns: boolean;
}

/**
 * Privacy scope for an entity
 */
export interface PrivacyScope {
  /** Base privacy level */
  readonly privacyLevel: PrivacyLevel;

  /** Granular telemetry consent */
  readonly telemetryConsent: TelemetryConsent;

  /** Optional: Specific users/groups this is shared with */
  readonly sharedWith?: readonly UserId[];

  /** Optional: Expiration for shared access */
  readonly sharingExpires?: Timestamp;
}

// -----------------------------------------------------------------------------
// SYNC & VERSIONING - Conflict resolution and merging
// -----------------------------------------------------------------------------

/**
 * Merge strategy for conflict resolution
 */
export type MergeStrategy =
  | "lww" // Last-write-wins (timestamp-based)
  | "crdt" // Conflict-free replicated data type
  | "manual" // Requires user resolution
  | "merge_arrays" // Concatenate arrays, dedupe
  | "max" // Take maximum value
  | "min"; // Take minimum value

/**
 * Sync state for an entity
 */
export interface SyncState {
  /** Local revision number (monotonically increasing) */
  readonly rev: RevisionNumber;

  /** Merge strategy for this entity */
  readonly mergeStrategy: MergeStrategy;

  /** Last sync timestamp */
  readonly lastSyncAt?: Timestamp;

  /** Remote revision (if known) */
  readonly remoteRev?: RevisionNumber;

  /** Pending local changes not yet synced */
  readonly pendingSync: boolean;

  /** Conflict state (if any) */
  readonly conflictState?: ConflictState;
}

/**
 * Conflict information when sync fails
 */
export interface ConflictState {
  /** When conflict was detected */
  readonly detectedAt: Timestamp;

  /** Local version of conflicting data */
  readonly localVersion: unknown;

  /** Remote version of conflicting data */
  readonly remoteVersion: unknown;

  /** Suggested resolution (if any) */
  readonly suggestedResolution?: "keep_local" | "keep_remote" | "merge";
}

// -----------------------------------------------------------------------------
// BASE ENTITY - All LKGC objects inherit from this
// -----------------------------------------------------------------------------

/**
 * Valid ID types for LKGC entities
 */
export type AnyEntityId =
  | EntityId
  | NodeId
  | EdgeId
  | EventId
  | SessionId
  | ProposalId
  | SnapshotId;

/**
 * Base type for ALL LKGC entities
 * Ensures provenance, privacy, and sync are always present
 * Generic over ID type to allow NodeId, EdgeId, etc.
 */
export interface LKGCEntity<TId extends AnyEntityId = EntityId> {
  /** Unique identifier */
  readonly id: TId;

  /** Provenance information */
  readonly provenance: Provenance;

  /** Privacy scope */
  readonly privacy: PrivacyScope;

  /** Sync state */
  readonly sync: SyncState;

  /** Soft deletion marker */
  readonly deletedAt?: Timestamp;

  /** Optional: Tags for organization */
  readonly tags?: readonly string[];

  /** Optional: Arbitrary metadata (plugin-specific, etc.) */
  readonly metadata?: Readonly<Record<string, unknown>>;
}

// -----------------------------------------------------------------------------
// FACTORY HELPERS - Create foundation objects with defaults
// -----------------------------------------------------------------------------

/**
 * Default telemetry consent (conservative)
 */
export const DEFAULT_TELEMETRY_CONSENT: TelemetryConsent = {
  events: true,
  text: false,
  audio: false,
  performance: true,
  errors: true,
  usagePatterns: true,
} as const;

/**
 * Default privacy scope
 */
export const DEFAULT_PRIVACY_SCOPE: PrivacyScope = {
  privacyLevel: "private",
  telemetryConsent: DEFAULT_TELEMETRY_CONSENT,
} as const;

// -----------------------------------------------------------------------------
// UTILITY TYPES
// -----------------------------------------------------------------------------

/**
 * Extract the ID type from an entity type
 */
export type IdOf<T extends LKGCEntity> = T["id"];

/**
 * Make selected fields optional
 */
export type PartialBy<T, K extends keyof T> = Omit<T, K> & Partial<Pick<T, K>>;

/**
 * Make all fields except selected ones optional
 */
export type RequireOnly<T, K extends keyof T> = Partial<T> & Pick<T, K>;

/**
 * Deep readonly type
 */
export type DeepReadonly<T> = T extends (infer U)[]
  ? readonly DeepReadonly<U>[]
  : T extends object
    ? { readonly [K in keyof T]: DeepReadonly<T[K]> }
    : T;

/**
 * Numeric range type (for validation documentation)
 */
export interface NumericRange {
  readonly min: number;
  readonly max: number;
  readonly step?: number;
}

/**
 * Normalized value in [0, 1]
 */
export type NormalizedValue = Brand<number, "NormalizedValue">;

/**
 * Score that can be negative (e.g., -1 to 1)
 */
export type BipolarScore = Brand<number, "BipolarScore">;

/**
 * Percentage (0-100)
 */
export type Percentage = Brand<number, "Percentage">;
